# -*- coding: utf-8 -*-
from . import sgi_base
from . import sgi_area
from . import sgi_norm
from . import sgi_alert_source
from . import sgi_legal
from . import sgi_context
from . import sgi_process
from . import sgi_process_procedure
from . import sgi_document
from . import sgi_doc_change
from . import sgi_nonconformity
from . import sgi_complaint
from . import sgi_improvement
from . import sgi_integration
from . import sgi_policy
from . import sgi_objective
from . import sgi_indicator
from . import sgi_audit
from . import sgi_risk
from . import sgi_supplier_eval
from . import sgi_management_review
from . import sgi_control_plan
from . import sgi_calibration
from . import sgi_fmea
from . import sgi_ppap
from . import sgi_incident
from . import sgi_competence
from . import sgi_format_map
from . import sgi_sales_budget
from . import sgi_sales_budget_line
from . import sgi_sales_budget_import
from . import sgi_diagnostic
from . import sgi_emergency
from . import sgi_msa
from . import sgi_settings
from . import sgi_sign_elearning
from . import sgi_cron
