# -*- coding: utf-8 -*-
from . import test_nc_flow
from . import test_doc_change
from . import test_process_map
from . import test_acks
from . import test_indicators
from . import test_audit
from . import test_risk
from . import test_mgmt_review
from . import test_calibration
from . import test_fmea
from . import test_ppap
from . import test_incident
from . import test_competence
from . import test_pegamento
from . import test_escalate_nc
from . import test_kpi_fase4
from . import test_retro_vinculacion
from . import test_process_map_46
from . import test_sgi_format_map
from . import test_flows_48
from . import test_ola0
from . import test_ola1
from . import test_ola2
from . import test_procedure
from . import test_ola_a_security
from . import test_ola_a_procedure
from . import test_ola_b
from . import test_view_file
from . import test_kpi20
from . import test_sales_budget
from . import test_alert_source
from . import test_fase7
from . import test_fase8
from . import test_diagnostic_otd
from . import test_mywork
from . import test_fase9
from . import test_fase10
from . import test_audit_hardening
from . import test_ola_certificable
from . import test_sign_elearning
from . import test_expansion_kpis
from . import test_catalog_fase1
from . import test_structure
from . import test_spec
from . import test_coa
from . import test_release
from . import test_indicator_detail
from . import test_indicator_i3
from . import test_indicator_p21
from . import test_indicator_formula
from . import test_indicator_plan
from . import test_indicator_trajectory
from . import test_my_procedure
from . import test_structure_sgi
from . import test_cleanup_45
from . import test_perm_auditor
from . import test_epp
from . import test_nc_deadlines
from . import test_audit_pr3
from . import test_pr4_docs_legal
from . import test_pr5_direction
from . import test_pr6_external
from . import test_pr7_replaces
from . import test_hierarchy
from . import test_links
