# -*- coding: utf-8 -*-
from . import test_nc_flow
from . import test_doc_change
from . import test_process_map
from . import test_acks
from . import test_indicators
from . import test_audit
from . import test_risk
from . import test_mgmt_review
from . import test_calibration
from . import test_fmea
from . import test_ppap
from . import test_incident
from . import test_competence
from . import test_pegamento
from . import test_escalate_nc
from . import test_kpi_fase4
from . import test_retro_vinculacion
from . import test_process_map_46
from . import test_sgi_format_map
from . import test_flows_48
from . import test_ola0
from . import test_ola1
from . import test_ola2
from . import test_procedure
from . import test_ola_a_security
from . import test_ola_a_procedure
from . import test_ola_b
from . import test_view_file
from . import test_kpi20
from . import test_sales_budget
from . import test_alert_source
