# -*- coding: utf-8 -*-
from . import test_nc_flow
from . import test_doc_change
from . import test_process_map
from . import test_acks
from . import test_indicators
from . import test_audit
from . import test_risk
from . import test_mgmt_review
from . import test_calibration
from . import test_fmea
from . import test_ppap
from . import test_incident
from . import test_competence
from . import test_pegamento
from . import test_escalate_nc
from . import test_retro_vinculacion
from . import test_process_map_46
from . import test_sgi_format_map
from . import test_format_map_documento
from . import test_replaced_by_process
from . import test_clave_anterior
from . import test_flows_48
from . import test_ola0
from . import test_ola1
from . import test_ola2
from . import test_procedure
from . import test_ola_a_security
from . import test_ola_a_procedure
from . import test_ola_b
from . import test_view_file
from . import test_kpi20
from . import test_alert_source
from . import test_fase7
from . import test_fase8
from . import test_diagnostic_otd
from . import test_mywork
from . import test_fase9
from . import test_fase10
from . import test_audit_hardening
from . import test_ola_certificable
from . import test_sign_elearning
from . import test_expansion_kpis
from . import test_catalog_fase1
from . import test_structure
from . import test_spec
from . import test_coa
from . import test_release
from . import test_indicator_detail
from . import test_indicator_i3
from . import test_indicator_p21
from . import test_indicator_formula
from . import test_indicator_plan
from . import test_indicator_trajectory
from . import test_my_procedure
from . import test_structure_sgi
from . import test_cleanup_45
from . import test_perm_auditor
from . import test_epp
from . import test_nc_deadlines
from . import test_audit_pr3
from . import test_pr4_docs_legal
from . import test_pr5_direction
from . import test_pr6_external
from . import test_pr7_replaces
from . import test_hierarchy
from . import test_links
from . import test_diagram_iso
from . import test_diagram_view
from . import test_my_procedure_ui
from . import test_kpi_fields
from . import test_excel_migration
from . import test_mp_change
from . import test_my_pending
from . import test_approval_native
from . import test_relative_roles
from . import test_role_audit
from . import test_cleanup_b10
from . import test_business_line
from . import test_doc_change_sign
from . import test_sign_builder
from . import test_my_procedure_sign
from . import test_due_long
from . import test_nc_origins
from . import test_external_doc
from . import test_hse_records
from . import test_capture_reply
from . import test_norm_compliance
from . import test_archived_filters
from . import test_update_respects_mast
from . import test_security_entrega1
from . import test_entrega1b
from . import test_entrega1c
from . import test_export_payload
from . import test_integridad
from . import test_multicompany
from . import test_menu_tree
from . import test_entrega4
from . import test_bandeja
from . import test_avisos_crons
from . import test_calibracion_avisos
from . import test_dropbox_section
from . import test_legacy_routine
from . import test_dropbox_key
from . import test_indicadores_571
from . import test_procesos_viejos
from . import test_siembras_y_funciones
from . import test_legado
from . import test_studio_cleanup
from . import test_weekly_overdue
from . import test_indicadores_2
from . import test_zona_horaria
from . import test_medicion_robusta
from . import test_rendimiento
from . import test_checklist_pin
from . import test_reclamaciones
from . import test_nomenclatura_pantallas
from . import test_fichas_busquedas
from . import test_herencias_propias
from . import test_vistas_pulido
from . import test_env_aspect
from . import test_work_permit
from . import test_loto
from . import test_hallazgos_evaluaciones
from . import test_sst_links
from . import test_format_map_varios
from . import test_format_map_operaciones
from . import test_laboratorio
from . import test_etiquetas_lote
from . import test_menus_entregables
from . import test_entregables_modelo
from . import test_vistas_pulido_45
from . import test_formatos_bloque3
from . import test_indicadores_5790
from . import test_candados_evidencia
from . import test_usted
from . import test_nc_auditoria_evidencia
from . import test_portal_nc_http
from . import test_sgi_en_planta
from . import test_sgi_en_planta_tour
from . import test_rendimiento_robustez
from . import test_sst_ambiente
from . import test_clausulas_revision
from . import test_interfaz
