{
    'name': 'Quimibond Intelligence System',
    'version': '19.0.3.1.0',
    'category': 'Productivity',
    'summary': 'Knowledge Graph + Communication Intelligence para Quimibond.',
    'description': 'Cerebro de inteligencia empresarial: emails, Odoo ERP, knowledge graph, Claude AI.',
    'author': 'Quimibond',
    'website': 'https://quimibond.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'sale',
        'account',
        'purchase',
    ],
    'external_dependencies': {
        'python': [
            'google.auth',
            'googleapiclient',
            'httpx',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'data/ir_cron_data.xml',
        'views/intelligence_briefing_views.xml',
        'views/intelligence_alert_views.xml',
        'views/intelligence_action_views.xml',
        'views/intelligence_query_views.xml',
        'views/res_partner_views.xml',
        'views/intelligence_config_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
